/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router, manually curated for PulseDeck's SoybeanAdmin base.

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'alerts',
    path: '/alerts',
    component: 'layout.base$view.alerts',
    meta: {
      title: '通知告警',
      icon: 'mdi:bell-badge-outline',
      order: 5,
      i18nKey: 'route.alerts'
    }
  },
  {
    name: 'commands',
    path: '/commands',
    component: 'layout.base$view.commands',
    meta: {
      title: '命令队列',
      icon: 'mdi:console-line',
      order: 6,
      i18nKey: 'route.commands'
    }
  },
  {
    name: 'dashboard',
    path: '/dashboard',
    component: 'layout.base$view.dashboard',
    meta: {
      title: '工作台',
      icon: 'mdi:view-dashboard-outline',
      order: 1,
      i18nKey: 'route.dashboard'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'nodes',
    path: '/nodes',
    component: 'layout.base$view.nodes',
    meta: {
      title: '节点管理',
      icon: 'mdi:server-network',
      order: 2,
      i18nKey: 'route.nodes'
    }
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      title: '系统设置',
      icon: 'mdi:tune-variant',
      order: 7,
      i18nKey: 'route.settings'
    }
  },
  {
    name: 'sing-box',
    path: '/sing-box',
    component: 'layout.base$view.sing-box',
    meta: {
      title: 'sing-box 配置',
      icon: 'mdi:cog-transfer-outline',
      order: 3,
      i18nKey: 'route.sing-box'
    }
  },
  {
    name: 'subscriptions',
    path: '/subscriptions',
    component: 'layout.base$view.subscriptions',
    meta: {
      title: '订阅分发',
      icon: 'mdi:link-variant',
      order: 4,
      i18nKey: 'route.subscriptions'
    }
  }
];
